CATEGORIAS = {
    "motor-ignicao": {
        "nome": "Motor e Ignição",
        "descricao": "Velas, correias de distribuição e acessórios, bombas de água e termóstatos.",
    },
    "travagem": {
        "nome": "Travagem",
        "descricao": "Discos, pastilhas, tambores, tubos e sensores ABS para travar em segurança.",
    },
    "suspensao-direcao": {
        "nome": "Suspensão e Direção",
        "descricao": "Amortecedores, braços, rótulas, bieletas e terminais de direção.",
    },
    "filtros-fluidos": {
        "nome": "Filtros e Fluidos",
        "descricao": "Óleos com normas VAG, líquido de travões, anticongelante e todos os filtros.",
    },
    "transmissao-embraiagem": {
        "nome": "Transmissão e Embraiagem",
        "descricao": "Óleo DSG, kits de embraiagem, homocinéticas e coxins da caixa.",
    },
    "escapamento": {
        "nome": "Escapamento",
        "descricao": "Silenciadores, catalisadores, filtro de partículas, sondas lambda e juntas flexíveis.",
    },
    "eletricidade-iluminacao": {
        "nome": "Eletricidade e Iluminação",
        "descricao": "Lâmpadas, bateria, sensores TPMS, sensores de estacionamento e ABS.",
    },
    "acessorios-ferramentas": {
        "nome": "Acessórios e Ferramentas",
        "descricao": "Tapetes, escovas limpa-vidros, chaves de filtro, macacos e ferramentas de oficina.",
    },
    "pneus-jantes": {
        "nome": "Pneus e Jantes",
        "descricao": "Pneus por medida, jantes de liga leve e kits de reparação.",
    },
}

MODELOS = [
    "SEAT Arona (2017+)",
    "SEAT Ibiza (2017+)",
    "SEAT Ateca (2016+)",
    "VW Polo (2017+)",
    "VW T-Cross (2019+)",
    "VW Golf (2019+)",
    "Audi A1 (2018+)",
    "Skoda Fabia (2014+)",
]

LOJAS = [
    {
        "nome": "Autodoc",
        "site": "https://www.autodoc.pt",
        "dominio": "autodoc.pt",
        "nota": "Catálogo enorme de peças VAG, muitas marcas com filtro por OEM.",
    },
    {
        "nome": "Mister-Auto",
        "site": "https://www.mister-auto.pt",
        "dominio": "mister-auto.pt",
        "nota": "Peças de desgaste e travagem com preços competitivos.",
    },
    {
        "nome": "Norauto",
        "site": "https://www.norauto.pt",
        "dominio": "norauto.pt",
        "nota": "Lojas físicas em Portugal + online; oficina e montagem de pneus.",
    },
    {
        "nome": "Feu Vert",
        "site": "https://www.feuvert.pt",
        "dominio": "feuvert.pt",
        "nota": "Rede com lojas físicas; pneus, peças e manutenção.",
    },
    {
        "nome": "Oscaro",
        "site": "https://www.oscaro.pt",
        "dominio": "oscaro.pt",
        "nota": "Peças por matrícula e referência OEM, entrega em Portugal.",
    },
    {
        "nome": "Sadas",
        "site": "https://www.sadas.pt",
        "dominio": "sadas.pt",
        "nota": "Referência nacional de peças de automóvel (distribuidor).",
    },
]

PARTES = [
    {
        "id": "oleo-5w30-507",
        "nome": "Óleo do motor 5W-30 (LongLife, baixo SAPS)",
        "categoria": "filtros-fluidos",
        "descricao": "Óleo recomendado para motores a gasolina TSI e diesel TDI com intervalo de manutenção longo (até 30.000 km / 2 anos).",
        "normas": ["VW 504.00", "VW 507.00"],
        "especificacoes": ["ACEA C3", "API SN/SP"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "SEAT Arona 1.6 TDI", "VW Polo 1.0 TSI", "VW Golf 1.5 TSI", "Audi A1 1.0 TSI", "Skoda Fabia 1.0 TSI"],
        "referencias": ["VW G052195M2", "VW G052195M4", "VW 501049012", "Castrol Edge Professional LongLife III"],
        "marcas": {
            "original": "VW LongLife III (G052195) / Castrol Edge Professional LongLife III",
            "equivalente": "Shell Helix Ultra Professional, Mobil 1 ESP, Total Quartz INEO Long Life",
            "economica": "Comma X-Tech LL 5W-30, Eni i-Sint Tech, Mannol 507.00 (todas certificadas VW 507.00)",
        },
        "dica": "Qualquer óleo com certificação VW 507.00/504.00 na embalagem cumpre a especificação de fábrica. Não precisa de pagar mais pela marca vendida na concessionária.",
        "quando_trocar": "A cada 30.000 km ou 2 anos (intervalo LongLife), ou 15.000 km/1 ano em uso severo.",
        "quantidade": "4 litros (1.0 TSI) / 5,5 litros (1.5 TSI).",
    },
    {
        "id": "oleo-0w20-508",
        "nome": "Óleo do motor 0W-20 (norma VW 508.00/509.00)",
        "categoria": "filtros-fluidos",
        "descricao": "Óleo de baixa viscosidade para motores TSI mais recentes com filtro de partículas de gasolina (GPF). Não usar em motores sem esta norma.",
        "normas": ["VW 508.00", "VW 509.00"],
        "especificacoes": ["ACEA C5", "API SP"],
        "aplicacoes": ["SEAT Arona 1.0 TSI (produção recente)", "SEAT Arona 1.5 TSI", "VW Golf 8", "Audi A1 2021+"],
        "referencias": ["VW G052188M1", "VW G052188M2", "Castrol Edge Professional V 0W-20"],
        "marcas": {
            "original": "VW LongLife IV / Castrol Edge Professional V 0W-20",
            "equivalente": "Mobil 1 ESP x2, Shell Helix Ultra, Liqui Moly Top Tec 6200",
            "economica": "Comma X-Tech 0W-20, Mannol 508.00, Eni i-Sint (certificadas VW 508.00)",
        },
        "dica": "Verifique na tampa do óleo se está escrito 0W-20 (VW 508.00). Usar 5W-30 num motor que pede 0W-20 pode danificar o GPF.",
        "quando_trocar": "Intervalo LongLife: até 30.000 km / 2 anos.",
        "quantidade": "4 litros (1.0 TSI).",
    },
    {
        "id": "oleo-caixa-dsg",
        "nome": "Óleo da caixa DSG / transmissão",
        "categoria": "transmissao-embraiagem",
        "descricao": "Óleo específico para caixas de dupla embraiagem DSG (DQ200 a seco e DQ381 molhada) e caixas manuais MQ281.",
        "normas": ["VW TL 52525", "G052512", "G055025"],
        "especificacoes": ["OEM VAG específico por caixa"],
        "aplicacoes": ["SEAT Arona DSG 1.0 TSI", "SEAT Arona DSG 1.6 TDI", "VW Polo DSG"],
        "referencias": ["VW G052512A2 (DQ200)", "VW G055025A2", "VW G060726A2"],
        "marcas": {
            "original": "VW G052512A2 / G055025A2 (conforme a caixa)",
            "equivalente": "Febi 29901, Liqui Moly Top Tec DSG, Ravenol DCT",
            "economica": "Mannol DSG, Comma (valores equivalentes com referência cruzada)",
        },
        "dica": "Confirme SEMPRE a referência exata da caixa (código no livro ou placa). Trocar DSG com óleo errado pode destruir a caixa.",
        "quando_trocar": "DSG molhado: a cada 60.000 km. Caixa manual: só se indicado no manual.",
        "quantidade": "Conforme caixa (2,1 L DQ200 / ~6 L DQ381).",
    },
    {
        "id": "refrigerante-g13",
        "nome": "Líquido de refrigeração G12++ / G13",
        "categoria": "filtros-fluidos",
        "descricao": "Anticongelante à base de Glicol, roxo (G13) ou rosa (G12++), conforme norma VW TL 774-J/F.",
        "normas": ["VW TL 774-F (G12++)", "VW TL 774-J (G13)"],
        "especificacoes": ["Não misturar com G11 (azul)"],
        "aplicacoes": ["Todos os modelos VAG a partir de 2005"],
        "referencias": ["VW G013A8JM1", "VW G012A8FM1", "VW G013A8J"],
        "marcas": {
            "original": "VW G13 (violeta) / G12++ (rosa) da marca VW",
            "equivalente": "Febi 37604 (G13), Ravenol HJC, Comma G30/G33",
            "economica": "Qualquer anticongelante G13/G12++ de marca branca com a norma TL 774 na etiqueta",
        },
        "dica": "Comprar anticongelante concentrado e diluir com água desmineralizada (50/50) é muito mais barato do que comprar já diluído.",
        "quando_trocar": "Conforme manual (geralmente 5 anos ou 200.000 km; completar quando necessário).",
        "quantidade": "~4,5 litros de mistura 50/50.",
    },
    {
        "id": "liquido-travoes-dot4",
        "nome": "Líquido de travões DOT 4 / DOT 4 Plus",
        "categoria": "filtros-fluidos",
        "descricao": "Líquido de travões sintético com ponto de ebulição elevado, norma VW TL 766-X.",
        "normas": ["ISO 4925 (DOT 4)", "VW TL 766-X", "FMVSS 116"],
        "especificacoes": ["Ponto de ebulição seco >= 230°C"],
        "aplicacoes": ["Todos os modelos VAG com ABS/ESC"],
        "referencias": ["VW B000750M3", "VW G004700M2"],
        "marcas": {
            "original": "VW Brake Fluid DOT4 Plus (G004700M2)",
            "equivalente": "ATE SL.6, Bosch DOT4, Castrol React DOT4",
            "economica": "Febi 34300, Motul DOT4, Mannol DOT4 (cumprem ISO 4925)",
        },
        "dica": "O líquido DOT 4 é higroscópico (absorve água). Troque a cada 2 anos, mesmo que o pedal pareça firme.",
        "quando_trocar": "A cada 2 anos, independentemente da quilometragem.",
        "quantidade": "1 litro para sangrar todo o circuito.",
    },
    {
        "id": "adblue",
        "nome": "AdBlue (UREA 32,5%)",
        "categoria": "filtros-fluidos",
        "descricao": "Solução de ureia para veículos Diesel com sistema SCR (AdBlue) para reduzir emissões NOx.",
        "normas": ["ISO 22241-1", "DIN 70070"],
        "especificacoes": ["Pureza 32,5%"],
        "aplicacoes": ["SEAT Arona 1.6 TDI", "SEAT Ateca 2.0 TDI", "VW Golf 2.0 TDI"],
        "referencias": ["VW G052973M1", "Conteiner VW 5L/10L"],
        "marcas": {
            "original": "VW AdBlue (embalagem original)",
            "equivalente": "AdBlue de marca (ARAL, TOTAL, Shell)",
            "economica": "AdBlue de supermercado/bomba (cumprindo ISO 22241) — igual para todos",
        },
        "dica": "Todo o AdBlue ISO 22241-1 é igual. Compre o mais barato; apenas evite embalagens que estejam abertas ou expostas ao sol.",
        "quando_trocar": "Repor quando o indicador avisar (autonomia ~2.400 km).",
        "quantidade": "10 L para Arona 1.6 TDI.",
    },
    {
        "id": "limpa-vidros",
        "nome": "Líquido limpa-vidros concentrado (anticongelante)",
        "categoria": "filtros-fluidos",
        "descricao": "Líquido concentrado para o circuito de lavagem, com anticongelante até -20°C no inverno.",
        "normas": ["Sem norma VAG específica"],
        "especificacoes": ["Diluição 1:3 ou 1:5"],
        "aplicacoes": ["Todos os modelos"],
        "referencias": ["VW G052164M2"],
        "marcas": {
            "original": "VW G052164M2",
            "equivalente": "Sonax, Liqui Moly, Febi",
            "economica": "Concentrados de marca branca de supermercado (são essencialmente o mesmo)",
        },
        "dica": "No inverno use versão com proteção -20°C para não congelar os bicos e o depósito.",
        "quando_trocar": "Repor quando o nível está baixo.",
        "quantidade": "1 litro concentrado por estação.",
    },
    {
        "id": "filtro-oleo",
        "nome": "Filtro de óleo",
        "categoria": "filtros-fluidos",
        "descricao": "Filtro de óleo do motor, cartucho ou tipo roscado conforme motor (EA211/EA288).",
        "normas": ["OEM VAG", "Dimensões conforme motor"],
        "especificacoes": ["Parafuso da tampa do filtro 32 mm"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "SEAT Arona 1.6 TDI", "VW Polo", "VW Golf", "Audi A1"],
        "referencias": ["VW 04E115561C (EA211)", "VW 04E115561H", "VW 04L115561C (EA288)"],
        "marcas": {
            "original": "Mann-Hummel / Hengst (fabricantes OEM VW)",
            "equivalente": "Mahle, Bosch, UFI, WIX, Knecht",
            "economica": "Filtron, CoopersFiaam, Blue Print, Corteco, Starline",
        },
        "dica": "O filtro de óleo da Arona 1.0 TSI (04E115561C) é o mesmo do Polo e Ibiza — compre pela referência e não pela marca para comparar preços.",
        "quando_trocar": "A cada troca de óleo (15.000–30.000 km).",
        "quantidade": "1 unidade.",
    },
    {
        "id": "filtro-ar",
        "nome": "Filtro de ar do motor",
        "categoria": "filtros-fluidos",
        "descricao": "Filtro de ar do motor, elemento plano em caixa plástica no motor TSI/TDI.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Substituir sem ferramenta especial"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "SEAT Arona 1.6 TDI"],
        "referencias": ["VW 04E129620K", "VW 04E129620C", "VW 04E129620G"],
        "marcas": {
            "original": "Mann-Hummel / Mahle (OEM)",
            "equivalente": "Bosch, Hengst, UFI, Knecht",
            "economica": "Filtron, CoopersFiaam, Blue Print, Corteco",
        },
        "dica": "Filtro de ar é uma peça simples: as marcas económicas (Filtron ~5€) têm boa qualidade. Troque em casa em 5 minutos.",
        "quando_trocar": "A cada 30.000–60.000 km ou conforme manual (intervalo 1.0 TSI: ~60.000 km).",
        "quantidade": "1 unidade.",
    },
    {
        "id": "filtro-habitaculo",
        "nome": "Filtro de habitáculo (pólen/cabine)",
        "categoria": "filtros-fluidos",
        "descricao": "Filtro do ar condicionado e aquecimento, com opção de carbono ativado.",
        "normas": ["OEM VAG", "Partículas + gás (carvão)"],
        "especificacoes": ["Montagem atrás do porta-luvas"],
        "aplicacoes": ["SEAT Arona", "SEAT Ibiza", "VW Polo", "VW T-Cross", "Audi A1"],
        "referencias": ["VW 5Q0819653", "VW 5Q0819653B"],
        "marcas": {
            "original": "Mann (CUK26010) / Hengst",
            "equivalente": "Bosch, Mahle, UFI, Valeo",
            "economica": "Filtron, CoopersFiaam, Corteco, Blue Print",
        },
        "dica": "Escolha a versão de carvão ativado (filtra pólen E gases) — custa pouco mais e o ar fica muito melhor no verão.",
        "quando_trocar": "A cada 15.000–30.000 km (recomendado anualmente).",
        "quantidade": "1 unidade.",
    },
    {
        "id": "filtro-combustivel",
        "nome": "Filtro de combustível",
        "categoria": "filtros-fluidos",
        "descricao": "Filtro do circuito de combustível (nos TDI fica debaixo do carro; nos TSI mais recentes é integrado na bomba).",
        "normas": ["OEM VAG"],
        "especificacoes": ["TDI: troca com mangueiras de retenção"],
        "aplicacoes": ["SEAT Arona 1.6 TDI", "SEAT Arona 1.0 TSI (verificar se aplicável)"],
        "referencias": ["VW 5Q0127401N (TDI)", "VW 04E127177 (TSI)"],
        "marcas": {
            "original": "Mann / Mahle / Bosch (OEM)",
            "equivalente": "Bosch, UFI, Hengst",
            "economica": "Filtron, CoopersFiaam, Blue Print, Corteco",
        },
        "dica": "Nos TSI recentes o filtro é 'lifetime' (integrado na bomba); nos TDI verifique sempre as duas mangueiras de retenção.",
        "quando_trocar": "TDI: a cada 60.000 km. TSI: apenas se houver problemas.",
        "quantidade": "1 unidade + mangueiras de retenção.",
    },
    {
        "id": "pastilhas-travao",
        "nome": "Pastilhas de travão dianteiras",
        "categoria": "travagem",
        "descricao": "Jogo de pastilhas de travão dianteiras com sensor de desgaste para Arona (pinça 54 mm).",
        "normas": ["ECE R90 (certificação de segurança)"],
        "especificacoes": ["Incluir sensor de desgaste (VW 5Q0698151)"],
        "aplicacoes": ["SEAT Arona 1.0/1.5 TSI (dianteiras)", "SEAT Arona 1.6 TDI"],
        "referencias": ["VW 5Q0698151F", "VW 5Q0698151M", "Sensor 5Q0698151"],
        "marcas": {
            "original": "TRW / Textar / Jurid (fornecedores VW)",
            "equivalente": "ATE, Bosch, Brembo, Pagid, Febi",
            "economica": "Valeo, Ferodo (custo-médio), RIDEX, A.B.S., Stark",
        },
        "dica": "As pastilhas originais são muitas vezes TRW ou Textar vendidas com caixa VW. Compre as pastilhas TRW/Textar pela marca (30-50% mais baratas) e o sensor de desgaste à parte.",
        "quando_trocar": "Quando a espessura < 2 mm ou o avisador acende.",
        "quantidade": "1 jogo (2 eixos) dianteiro + sensor.",
    },
    {
        "id": "discos-travao",
        "nome": "Discos de travão dianteiros",
        "categoria": "travagem",
        "descricao": "Discos de travão dianteiros ventilados (280 mm) com pastilhas novas.",
        "normas": ["ECE R90"],
        "especificacoes": ["280 mm ventilado, espessura 22 mm"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI"],
        "referencias": ["VW 5Q0615301AD", "VW 5Q0615301A", "VW 8V0615301A"],
        "marcas": {
            "original": "TRW / Brembo (OEM)",
            "equivalente": "ATE, Bosch, Zimmermann, Textar",
            "economica": "RIDEX, A.B.S., Stark, Blue Print",
        },
        "dica": "Troque sempre discos e pastilhas ao mesmo tempo e por eixo. Discos RIDEX/A.B.S. (marcas Autodoc) são até 60% mais baratos e cumprem ECE R90.",
        "quando_trocar": "Quando os discos têm rebordo >1,5 mm ou vibração ao travar.",
        "quantidade": "2 discos + jogo de pastilhas.",
    },
    {
        "id": "pastilhas-travao-traseiras",
        "nome": "Pastilhas de travão traseiras (com travão de estacionamento elétrico)",
        "categoria": "travagem",
        "descricao": "Pastilhas traseiras para pinças com travão de estacionamento elétrico (EPB) — requerem recuo elétrico da pinça na troca.",
        "normas": ["ECE R90"],
        "especificacoes": ["EPB (travão elétrico) — recuo via OBD2/sistema"],
        "aplicacoes": ["SEAT Arona (traseiras)", "VW Polo", "VW T-Cross"],
        "referencias": ["VW 5Q0698451J", "VW 5Q0698451G"],
        "marcas": {
            "original": "TRW / Textar (OEM)",
            "equivalente": "ATE, Bosch, Brembo, Pagid",
            "economica": "Valeo, Ferodo, RIDEX, A.B.S.",
        },
        "dica": "Na troca, o travão elétrico precisa de ser recuado com scanner (ex.: VCDS/OBD11). Se não tem, peça à oficina apenas este serviço.",
        "quando_trocar": "Quando < 2 mm. As traseiras gastam menos que as dianteiras.",
        "quantidade": "1 jogo traseiro.",
    },
    {
        "id": "correia-distribuicao",
        "nome": "Kit de correia de distribuição (1.0 TSI)",
        "categoria": "motor-ignicao",
        "descricao": "Kit completo com correia dentada, tensor, rolo e bomba de água para motores EA211 1.0 TSI.",
        "normas": ["OEM VAG", "Intervalo definido por tempo"],
        "especificacoes": ["IA/INA kit, inclui bomba de água"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "SEAT Ibiza 1.0 TSI", "VW Polo 1.0 TSI"],
        "referencias": ["VW 04C109119A", "VW 04C109479H (bomba de água)", "Kit INA 530053410"],
        "marcas": {
            "original": "INA / Schaeffler (fabricante OEM da correia)",
            "equivalente": "ContiTech, Gates, SKF",
            "economica": "Optibelt, Blue Print, RIDEX (verificar qualidade do tensor)",
        },
        "dica": "O fabricante original da correia do 1.0 TSI é a INA/Schaeffler. Comprar o kit INA custa metade do kit 'original' da concessionária e é exatamente a mesma peça.",
        "quando_trocar": "1.0 TSI: a cada ~6 anos / 120.000 km (confirmar no manual — intervalo por idade).",
        "quantidade": "1 kit (correia + tensor + rolo + bomba de água).",
    },
    {
        "id": "correia-serpentina",
        "nome": "Correia de acessórios (serpentina)",
        "categoria": "motor-ignicao",
        "descricao": "Correia de acessórios com tensor para alternador e compressão do AC.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Trocada com o tensor"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.6 TDI"],
        "referencias": ["VW 04E903137P", "VW 04E903137"],
        "marcas": {
            "original": "ContiTech / Gates (OEM)",
            "equivalente": "ContiTech, Gates, SKF, Bosch",
            "economica": "Dayco, Optibelt, Blue Print",
        },
        "dica": "Se o tensor tem mola com folga ou a correia tem fissuras, troque ambos (kit). Correas ContiTech de marca branca são as mesmas que a VW usa.",
        "quando_trocar": "A cada 60.000–90.000 km ou se houver ruído.",
        "quantidade": "Correia + tensor (kit).",
    },
    {
        "id": "velas-ignicao",
        "nome": "Velas de ignição (1.0/1.5 TSI)",
        "categoria": "motor-ignicao",
        "descricao": "Velas de irídio/platina para motores TSI — 3 velas (1.0) ou 4 (1.5).",
        "normas": ["OEM VAG", "Thermal rating específico"],
        "especificacoes": ["Parafuso 14 mm, 2.500 rpm"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "VW Polo 1.0 TSI"],
        "referencias": ["VW 04E905601A", "VW 04C905601", "NGK 93313 / PLFER7A8EG"],
        "marcas": {
            "original": "NGK (OEM dos TSI)",
            "equivalente": "Bosch, Denso, Beru",
            "economica": "Beru, Bremi, Motaquip (especificação idêntica)",
        },
        "dica": "A vela de origem dos TSI é NGK. Compre NGK pela referência correta (93313) — é 3-4x mais barata do que a embalagem VW.",
        "quando_trocar": "A cada ~60.000 km ou conforme manual.",
        "quantidade": "3 velas (1.0 TSI) / 4 velas (1.5 TSI).",
    },
    {
        "id": "bateria-efb",
        "nome": "Bateria EFB 70 Ah (com start-stop)",
        "categoria": "eletricidade-iluminacao",
        "descricao": "Bateria EFB 70Ah/680A para Arona com sistema Start-Stop. Requer registo/codificação após troca.",
        "normas": ["EN 680A", "EFB (Enhanced Flooded Battery)"],
        "especificacoes": ["Dimensões L242xW175xH190", "Terminal EN"],
        "aplicacoes": ["SEAT Arona (com Start-Stop)", "SEAT Ibiza", "VW Polo"],
        "referencias": ["VW 5Q0915105D", "EFB 70 680A"],
        "marcas": {
            "original": "Varta (OEM)", 
            "equivalente": "Bosch S5, Banner, Exide",
            "economica": "Lion (L5 70Ah), Lucas, Varta Promotive (mesma fábrica que a 'original')",
        },
        "dica": "A Varta é a bateria de fábrica dos VAG. A 'Varta Promotive' (linha barata) é fabricada pela mesma fábrica — qualidade igual, preço menor. Não se esqueça do registo da bateria.",
        "quando_trocar": "Quando a tensão em repouso < 12,3V ou falha o start-stop.",
        "quantidade": "1 bateria.",
    },
    {
        "id": "escovas-limpavidros",
        "nome": "Escovas do limpa-vidros (sem espinha)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Escovas flat (aero) dianteiras para Arona, sem espinha, com adaptador específico VW.",
        "normas": ["OEM VAG", "Comprimentos específicos do Arona"],
        "especificacoes": ["600 mm / 400 mm (confirmar no manual)"],
        "aplicacoes": ["SEAT Arona", "SEAT Ibiza", "VW Polo"],
        "referencias": ["VW 6R1955425B", "VW 6R1955426B", "Bosch A399S"],
        "marcas": {
            "original": "Bosch Aerotwin (OEM)",
            "equivalente": "Valeo SWF, Denso, Mitsuba",
            "economica": "Champion, Bosch genérico, Magneti Marelli (marcas com boa relação preço)",
        },
        "dica": "Escovas de marca branca com o mesmo adaptador custam 3-4€ e duram o mesmo. Troque-as ao primeiro sinal de risco.",
        "quando_trocar": "A cada 6–12 meses.",
        "quantidade": "2 escovas dianteiras.",
    },
    {
        "id": "lampadas-h7",
        "nome": "Lâmpadas H7 (máximos/médios)",
        "categoria": "eletricidade-iluminacao",
        "descricao": "Lâmpadas H7 para faróis (médios) do Arona. Versões halógenas comuns; verificar tipo de farol.",
        "normas": ["ECE R37", "E-mark"],
        "especificacoes": ["H7 12V 55W"],
        "aplicacoes": ["SEAT Arona (faróis halogénio)", "SEAT Ibiza"],
        "referencias": ["VW 5F0941731", "Philips H7", "Osram H7"],
        "marcas": {
            "original": "Philips / Osram (OEM)",
            "equivalente": "Philips LongLife, Osram Night Breaker, Bosch H7",
            "economica": "Marca branca E-mark certificada (mais fraca em alcance)",
        },
        "dica": "Compre H7 LongLife (duração) ou Night Breaker (alcance) em vez da marca branca — a diferença de visibilidade à noite justifica 2-3€.",
        "quando_trocar": "Quando queimada; troque sempre em par.",
        "quantidade": "2 lâmpadas.",
    },
    {
        "id": "pneus-215-55-r17",
        "nome": "Pneus 215/55 R17 (medida padrão Arona)",
        "categoria": "pneus-jantes",
        "descricao": "Pneus de verão 215/55 R17 94V/W para jantes 6,5Jx17 (medida de fábrica do Arona).",
        "normas": ["Etiqueta UE (rolagem/chuva/ruído)", "Índice carga 94 (670 kg)", "Velocidade V/W"],
        "especificacoes": ["Pressão recomendada ~2,3–2,6 bar", "Verificar etiqueta da porta"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "SEAT Arona 1.6 TDI"],
        "referencias": ["Medida 215/55 R17", "Índice 94V ou 94W"],
        "marcas": {
            "original": "Michelin Primacy 4 / Continental PremiumContact (equipamento de fábrica)",
            "equivalente": "Goodyear EfficientGrip Performance 2, Hankook Kinergy 4S2, Pirelli Cinturato P7",
            "economica": "Nexen N'Fera Primus, Kumho Ecowing, Laufenn, Linglong (custo-benefício)",
        },
        "dica": "Os pneus de fábrica do Arona são premium, mas marcas como Nexen/Kumho dão 80% da performance por metade do preço. Compare sempre a etiqueta UE (rolagem + chuva).",
        "quando_trocar": "Quando a profundidade < 1,6 mm (legal) ou sinais de envelhecimento (5+ anos).",
        "quantidade": "4 pneus (ou em pares).",
    },
    {
        "id": "pneus-215-45-r18",
        "nome": "Pneus 215/45 R18 (jantes opcionais)",
        "categoria": "pneus-jantes",
        "descricao": "Pneus 215/45 R18 para as jantes de 18\" opcionais do Arona (Xperience / FR).",
        "normas": ["Etiqueta UE", "Índice carga 89+", "Velocidade V/W/Y"],
        "especificacoes": ["Pressão conforme porta"],
        "aplicacoes": ["SEAT Arona FR", "SEAT Arona Xperience"],
        "referencias": ["Medida 215/45 R18", "Índice 89Y"],
        "marcas": {
            "original": "Continental / Bridgestone (equipamento de fábrica)",
            "equivalente": "Michelin Primacy 4, Pirelli P7, Goodyear",
            "economica": "Nexen, Falken, Toyo, Landsail (custo-benefício)",
        },
        "dica": "Jantes de 18\" têm pneus mais caros e mais sensíveis a buracos. Se o conforto e o preço importam, considere baixar para 17\" com o mesmo perímetro.",
        "quando_trocar": "Profundidade < 1,6 mm ou envelhecimento.",
        "quantidade": "4 pneus.",
    },
    {
        "id": "pneus-215-60-r16",
        "nome": "Pneus 215/60 R16 (medida de conforto)",
        "categoria": "pneus-jantes",
        "descricao": "Pneus 215/60 R16 para jantes 6,5Jx16 — a medida de menor consumo e mais conforto para o Arona.",
        "normas": ["Etiqueta UE", "Índice 94V/H"],
        "especificacoes": ["Perfil mais alto = mais conforto"],
        "aplicacoes": ["SEAT Arona (versões de entrada)"],
        "referencias": ["Medida 215/60 R16"],
        "marcas": {
            "original": "Equipamento de fábrica variável",
            "equivalente": "Michelin, Continental, Goodyear",
            "economica": "Nexen, Hankook, Falken (custo-benefício)",
        },
        "dica": "A 16\" é a medida mais económica para o Arona — pneus mais baratos, menor consumo e mais conforto. Ideal para quem faz muitos km.",
        "quando_trocar": "Profundidade < 1,6 mm.",
        "quantidade": "4 pneus.",
    },
    {
        "id": "pneus-inverno",
        "nome": "Pneus de inverno / All-Season",
        "categoria": "pneus-jantes",
        "descricao": "Pneus de inverno (3PMSF) ou All-Season para uso em climas frios/serra. Em Portugal continental os All-Season são mais práticos.",
        "normas": ["3PMSF (floco de neve)", "Etiqueta UE"],
        "especificacoes": ["Compromisso verão/inverno"],
        "aplicacoes": ["SEAT Arona (qualquer medida)"],
        "referencias": ["215/55 R17 all-season", "215/60 R16 all-season"],
        "marcas": {
            "original": "Bridgestone / Michelin CrossClimate",
            "equivalente": "Continental AllSeasonContact, Goodyear Vector 4Seasons",
            "economica": "Kumho Solus, Falken EuroAll Season, Laufenn i Fit",
        },
        "dica": "O Michelin CrossClimate é o líder all-season, mas o Kumho/Falken custa metade e é adequado para o clima português.",
        "quando_trocar": "All-season para todo o ano; inverno de novembro a março.",
        "quantidade": "4 pneus.",
    },
    {
        "id": "jantes-liga",
        "nome": "Jantes de liga leve (réplicas)",
        "categoria": "pneus-jantes",
        "descricao": "Jantes de liga leve 6,5Jx17 ET43 5x100 com pino central 57,1 mm — medidas corretas para o Arona.",
        "normas": ["PCD 5x100", "ET43", "Furo central 57,1", "Carga por roda >= 690 kg"],
        "especificacoes": ["Aperto 120 Nm (VAG)"],
        "aplicacoes": ["SEAT Arona (todas as versões)"],
        "referencias": ["VW 6F0601025L (jante Arona 17\")", "Medidas 6,5Jx17 ET43"],
        "marcas": {
            "original": "SEAT/VW jantes originais",
            "equivalente": "Alcar, AEZ, Rial (réplicas de qualidade)",
            "economica": "Réplicas Alcar/AEZ custam 1/3 do preço da original",
        },
        "dica": "Verifique SEMPRE o PCD (5x100), o ET (43) e o furo central (57,1) antes de comprar. Réplicas Alcar/AEZ são as mais fiáveis e baratas.",
        "quando_trocar": "Quando amolgadas/fissuradas — não reparar jantes fraturadas.",
        "quantidade": "4 jantes + parafusos (se necessário).",
    },
    {
        "id": "kit-reparacao-pneus",
        "nome": "Kit de reparação de pneus (sem roda sobresselente)",
        "categoria": "pneus-jantes",
        "descricao": "O Arona não tem roda sobresselente — traz compressor + vedante. Substitua o vedante vencido por um novo barato.",
        "normas": ["Sem norma específica"],
        "especificacoes": ["Vedante válido 4-5 anos", "Compressor 12V"],
        "aplicacoes": ["SEAT Arona (todos)"],
        "referencias": ["VW 5G0010001 (kit)", "Vedante VAG 1K0010012"],
        "marcas": {
            "original": "VW kit original",
            "equivalente": "Slime, Holts, Liqui Moly (vedante universal)",
            "economica": "Vedantes de marca branca cumprem o mesmo",
        },
        "dica": "Verifique a validade do vedante do kit — os vedantes vencidos não vedam. Compre um vedante novo genérico por 5€ em vez de pagar o kit completo na marca.",
        "quando_trocar": "Vedante vencido (4-5 anos) ou após utilização.",
        "quantidade": "1 vedante + compressor.",
    },
    {
        "id": "sensores-tpms",
        "nome": "Sensores de pressão de pneus (TPMS)",
        "categoria": "eletricidade-iluminacao",
        "descricao": "Sensores TPMS diretos nas jantes que comunicam com o painel de instrumentos.",
        "normas": ["433 MHz / 2,4 GHz (conforme veículo)"],
        "especificacoes": ["Codificação após montagem (VCDS)"],
        "aplicacoes": ["SEAT Arona com TPMS direto", "VW Polo", "Audi A1"],
        "referencias": ["VW 5Q0907273B", "VW 6R0907273"],
        "marcas": {
            "original": "Schrader / VAG (OEM)",
            "equivalente": "Schrader EZ-sensor, Huf, Alligator",
            "economica": "Sensores universais programáveis (ChipMax/Autel)",
        },
        "dica": "Se trocar para jantes novas de inverno, compre um segundo set de sensores programáveis — evita re-codificar a cada troca de rodas.",
        "quando_trocar": "Quando a pilha falha (5-7 anos) ou ao montar jantes novas.",
        "quantidade": "4 sensores + programação.",
    },
    {
        "id": "tapetes-interior",
        "nome": "Tapetes de borracha/têxteis (cabine)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Tapetes específicos para o Arona com fixação por rotação no piso (VAG usa sistema twist).",
        "normas": ["Fixação específica Arona (twist + gancho)"],
        "especificacoes": ["Dianteiros + traseiros"],
        "aplicacoes": ["SEAT Arona (2017+)"],
        "referencias": ["VW 6F1064550B (borracha)", "VW 6F1064551A"],
        "marcas": {
            "original": "SEAT tapetes originais",
            "equivalente": "Tapetes cortados à medida (borracha 3D)",
            "economica": "Tapetes universais cortados ou réplicas online (metade do preço)",
        },
        "dica": "Os tapetes de borracha 3D 'à medida' online custam 20-25€ vs 60€+ dos originais e protegem melhor. Confirme o sistema de fixação (twist).",
        "quando_trocar": "Quando gastos/rotos.",
        "quantidade": "Set completo (4 tapetes + mala).",
    },
    {
        "id": "tapete-mala",
        "nome": "Tapete/forro da mala (borracha)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Forro de borracha para a mala do Arona com rebordo elevado para proteger contra sujidade.",
        "normas": ["Recorte específico Arona"],
        "especificacoes": ["Mala ~400 litros"],
        "aplicacoes": ["SEAT Arona (2017+)"],
        "referencias": ["VW 6F8061531"],
        "marcas": {
            "original": "SEAT original (tapete de mala)",
            "equivalente": "Forros 3D online (corte específico)",
            "economica": "Forros genéricos recortados (20€) — mesma proteção",
        },
        "dica": "Um forro com rebordo evita que a sujidade passe para o tapete original — vale a pena o investimento de 20-25€.",
        "quando_trocar": "Quando danificado.",
        "quantidade": "1 forro de mala.",
    },
    {
        "id": "suporte-telemovel",
        "nome": "Suporte de telemóvel (ventoinha/tablier)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Suporte magnético ou com mola para ventoinha ou tablier, com carregamento sem fios opcional.",
        "normas": ["Sem norma específica"],
        "especificacoes": ["Compatível com ventoinhas do Arona"],
        "aplicacoes": ["SEAT Arona (qualquer versão)"],
        "referencias": ["Suportes universais"],
        "marcas": {
            "original": "SEAT acessório original (carregador wireless)",
            "equivalente": "Belkin, Spigen, Ugreen (qualidade)",
            "economica": "Suportes genéricos (5-10€) com a mesma função",
        },
        "dica": "Prefira suportes com carga sem fios de 15W para usar com Android Auto/Apple CarPlay sem cabos.",
        "quando_trocar": "Quando a ventosa perde aderência.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "barras-tejadilho",
        "nome": "Barras de tejadilho / cofres",
        "categoria": "acessorios-ferramentas",
        "descricao": "Barras de tejadilho específicas para o Arona com fixação nos pontos de montagem da calha.",
        "normas": ["Carga máxima dinâmica ~70 kg (confirmar)"],
        "especificacoes": ["Kit específico Arona", "Carga estática maior"],
        "aplicacoes": ["SEAT Arona (2017+)"],
        "referencias": ["SEAT 6F0071126", "Thule 745", "Atera"],
        "marcas": {
            "original": "SEAT/Thule original",
            "equivalente": "Thule, Atera, Mont Blanc (marcas de referência)",
            "economica": "Barras genéricas (40-80€) com boa fixação",
        },
        "dica": "Verifique sempre a carga máxima dinâmica das barras e do tejadilho do Arona (no manual) antes de transportar carga.",
        "quando_trocar": "Quando a borracha/garras degradam.",
        "quantidade": "1 par de barras.",
    },
    {
        "id": "organizador-mala",
        "nome": "Organizador de mala / cofre de carga",
        "categoria": "acessorios-ferramentas",
        "descricao": "Cofre/organizador dobrável para a mala do Arona, com divisórias e fixação anti-deslize.",
        "normas": ["Sem norma específica"],
        "especificacoes": ["Dobrável", "Com divisórias"],
        "aplicacoes": ["SEAT Arona (todos)"],
        "referencias": ["Organizadores universais"],
        "marcas": {
            "original": "SEAT cofre de carga original",
            "equivalente": "Cofres de marca (MicksGarage, Halfords)",
            "economica": "Cofres genéricos dobráveis (10-15€)",
        },
        "dica": "Um cofre dobrável com divisórias evita que as compras deslizem — peça barata que faz muita diferença no dia a dia.",
        "quando_trocar": "Quando as costuras rompem.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "carregador-usb-c",
        "nome": "Carregador USB-C / adaptador 12V",
        "categoria": "acessorios-ferramentas",
        "descricao": "Adaptador para a tomada 12V com duas saídas USB-C/USB-A e carregamento rápido (PD).",
        "normas": ["USB-PD 3.0", "QC 3.0"],
        "especificacoes": ["Potência >= 30W"],
        "aplicacoes": ["SEAT Arona (tomada 12V central)"],
        "referencias": ["Acessórios universais"],
        "marcas": {
            "original": "SEAT carregador original",
            "equivalente": "Anker, Ugreen, Baseus (qualidade)",
            "economica": "Adaptadores genéricos (8-15€)",
        },
        "dica": "Evite adaptadores baratos de alta potência que podem aquecer; escolha marcas com proteção térmica (Anker/Ugreen).",
        "quando_trocar": "Quando o encaixe frouxo.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "escova-neve-gelo",
        "nome": "Escova para neve/gelo + raspa",
        "categoria": "acessorios-ferramentas",
        "descricao": "Escova com raspa de gelo para o inverno — útil em serras e no norte de Portugal.",
        "normas": ["Sem norma específica"],
        "especificacoes": ["Cabo telescópico opcional"],
        "aplicacoes": ["Todos os modelos"],
        "referencias": ["Acessórios universais"],
        "marcas": {
            "original": "SEAT acessório original",
            "equivalente": "Marca de qualidade (borracha macia)",
            "economica": "Escovas genéricas (3-5€)",
        },
        "dica": "Compre uma escova com raspa de borracha (não plástico duro) para não riscar o vidro.",
        "quando_trocar": "Quando as cerdas/raspa gastam.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "chave-dinamometrica",
        "nome": "Chave dinamométrica (3/8\" e 1/2\")",
        "categoria": "acessorios-ferramentas",
        "descricao": "Chave dinamométrica para apertar com o binário correto (rodas VAG: 120 Nm; velas: 25-30 Nm).",
        "normas": ["ISO 6789-1", "Erro +/- 4%"],
        "especificacoes": ["Faixa 20-210 Nm (1/2\")", "Faixa 5-60 Nm (3/8\")"],
        "aplicacoes": ["Todas as oficinas e DIY"],
        "referencias": ["Binários VAG: rodas 120 Nm", "Velas 25 Nm"],
        "marcas": {
            "original": "Gedore, Stahlwille (referência de oficina)",
            "equivalente": "Facom, Hazet, Wera (premium)",
            "economica": "Teng Tools, RIDGID, marcas brancas certificadas ISO 6789 (25-40€)",
        },
        "dica": "Para uso doméstico, uma chave de marca branca certificada ISO 6789 com calibração é suficiente. Guarde a 30% do binário máximo e recalibre a cada 1-2 anos.",
        "quando_trocar": "Quando perde calibração (recalibrar).",
        "quantidade": "1 chave + encaixes.",
    },
    {
        "id": "scanner-obd2",
        "nome": "Scanner OBD2 / VCDS / OBD11",
        "categoria": "acessorios-ferramentas",
        "descricao": "Scanner de diagnóstico para ler códigos de erro, recuar travão elétrico (EPB) e registar bateria nos VAG.",
        "normas": ["OBD-II", "Protocolos VAG"],
        "especificacoes": ["VCDS (ROSSTECH) ou OBDeleven", "Bluetooth/WiFi"],
        "aplicacoes": ["SEAT Arona", "Todos os VAG"],
        "referencias": ["VCDS HEX-V2", "OBDeleven Pro", "OBDLink CX"],
        "marcas": {
            "original": "VCDS ROSSTECH (oficial VAG)",
            "equivalente": "OBDeleven (app + Bluetooth)",
            "economica": "Adaptadores ELM327 genéricos (apenas leitura básica)",
        },
        "dica": "O OBDeleven (30-60€) permite funções VAG (recuo EPB, registo bateria, codificações) por uma fração do custo do VCDS oficial.",
        "quando_trocar": "Quando a app/protocolo fica obsoleto.",
        "quantidade": "1 dispositivo + app.",
    },
    {
        "id": "macaco-hidraulico",
        "nome": "Macaco hidráulico de garagem (2-3 t)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Macaco hidráulico tipo garrafa ou trolley com capacidade 2-3 toneladas para manutenção doméstica.",
        "normas": ["EN 1494", "Capacidade >= 2t"],
        "especificacoes": ["Altura mínima baixa (para baixos do Arona)"],
        "aplicacoes": ["Todas as oficinas e DIY"],
        "referencias": ["Macacos universais"],
        "marcas": {
            "original": "Craftsman, KTC (profissional)",
            "equivalente": "SGS, Draper, Teng Tools",
            "economica": "Macacos de marca branca EN 1494 (30-50€)",
        },
        "dica": "Nunca trabalhe debaixo do carro só com o macaco — use sempre cavaletes. Para o Arona, escolha um macaco com altura mínima < 150 mm.",
        "quando_trocar": "Quando perde pressão (verificar juntas).",
        "quantidade": "1 macaco + cavaletes.",
    },
    {
        "id": "cavaletes",
        "nome": "Cavaletes de apoio (2-3 t)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Cavaletes de segurança para apoiar o veículo após o macaco.",
        "normas": ["EN 1494", "Capacidade >= 2t por par"],
        "especificacoes": ["Ajustáveis em altura"],
        "aplicacoes": ["Todas as oficinas e DIY"],
        "referencias": ["Cavaletes universais"],
        "marcas": {
            "original": "Profissionais (KTC, SGS)",
            "equivalente": "Draper, Teng Tools",
            "economica": "Cavaletes de marca branca EN 1494 (20-30€ par)",
        },
        "dica": "Cavaletes são equipamento de segurança — prefira os com certificação EN 1494 e trava de segurança dupla.",
        "quando_trocar": "Quando deformados ou com jogo.",
        "quantidade": "1 par.",
    },
    {
        "id": "chave-filtros",
        "nome": "Chave para filtro de óleo (32 mm / cesto)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Chave de cesto ou sapatilha para remover o filtro de óleo (o 1.0 TSI usa tampa de 32 mm).",
        "normas": ["Ajustável"],
        "especificacoes": ["Tampa 32 mm (EA211)", "Cesto 74-82 mm"],
        "aplicacoes": ["SEAT Arona 1.0 TSI (tampa 32 mm)"],
        "referencias": ["Chaves universais"],
        "marcas": {
            "original": "Snap-on, Hazet (profissional)",
            "equivalente": "Teng Tools, Draper",
            "economica": "Chaves de marca branca (5-10€)",
        },
        "dica": "A tampa do filtro do 1.0 TSI é de plástico — use chave de 32 mm própria e nunca aperte em excesso (25 Nm).",
        "quando_trocar": "Quando deforma.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "jogo-chaves-caixa",
        "nome": "Jogo de chaves de caixa (métrico)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Jogo de caixas 1/4\" e 1/2\" métricas com catraca para manutenção geral VAG (10/13/16/17/19/21 mm).",
        "normas": ["Métrico (DIN 3124)"],
        "especificacoes": ["Medidas comuns VAG: 10, 13, 16, 17, 19, 21, 30 mm"],
        "aplicacoes": ["Todas as oficinas e DIY"],
        "referencias": ["Jogos universais 40-80 peças"],
        "marcas": {
            "original": "Snap-on, Gedore (profissional)",
            "equivalente": "Facom, Hazet, Wera",
            "economica": "Teng Tools, marca branca com garantia (20-40€)",
        },
        "dica": "Para DIY um jogo de 40-80 peças de marca branca com garantia serve. As medidas mais usadas nos VAG são 10, 16, 17 e 21 mm.",
        "quando_trocar": "Quando peças partem (garantia).",
        "quantidade": "1 jogo.",
    },
    {
        "id": "multimetro",
        "nome": "Multímetro digital",
        "categoria": "acessorios-ferramentas",
        "descricao": "Multímetro para diagnosticar bateria, alternador, fusíveis e sensores.",
        "normas": ["CAT II/CAT III", "IEC 61010"],
        "especificacoes": ["AC/DC, resistência, continuidade, tensão"],
        "aplicacoes": ["Todas as oficinas e DIY"],
        "referencias": ["Multímetros universais"],
        "marcas": {
            "original": "Fluke (referência profissional)",
            "equivalente": "Brymen, Uni-T (boa relação)",
            "economica": "Multímetros genéricos CAT III (15-25€)",
        },
        "dica": "Para automóvel basta um multímetro com medição de continuidade e tensão DC; verifique a bateria em repouso (>12,4V) e alternador (13,8-14,5V).",
        "quando_trocar": "Quando as pontas de prova gastam.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "compressao-molas",
        "nome": "Compressor de molas (suspensão)",
        "categoria": "acessorios-ferramentas",
        "descricao": "Compressor de molas de suspensão para troca de amortecedores em segurança.",
        "normas": ["Certificação de segurança"],
        "especificacoes": ["Molas dianteiras e traseiras"],
        "aplicacoes": ["Todas as oficinas e DIY"],
        "referencias": ["Compressores universais"],
        "marcas": {
            "original": "Klann, KTC (profissional)",
            "equivalente": "Draper, Sealey",
            "economica": "Compressores de marca branca (15-30€)",
        },
        "dica": "Trabalhar com molas comprimidas é perigoso — se não tem experiência, entregue a troca de amortecedores a uma oficina.",
        "quando_trocar": "Quando as garras deformam.",
        "quantidade": "1 par.",
    },
    {
        "id": "lampadas-led-verificacao",
        "nome": "Lâmpadas de verificação / luz de trabalho LED",
        "categoria": "acessorios-ferramentas",
        "descricao": "Luz de trabalho LED magnética para inspeção e reparações no escuro.",
        "normas": ["Sem norma específica"],
        "especificacoes": ["Bateria recarregável", "Base magnética"],
        "aplicacoes": ["Todas as oficinas e DIY"],
        "referencias": ["Luzes universais"],
        "marcas": {
            "original": "Bosch, Ledlenser (premium)",
            "equivalente": "Energizer, Worx",
            "economica": "Luzes LED genéricas (10-20€)",
        },
        "dica": "Prefira luzes com base magnética e gancho — fáceis de fixar no capot ou chassis do Arona durante a manutenção.",
        "quando_trocar": "Quando a bateria degrada.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "bomba-agua",
        "nome": "Bomba de água (1.0/1.5 TSI)",
        "categoria": "motor-ignicao",
        "descricao": "Bomba de água do circuito de refrigeração, trocada em conjunto com a correia de distribuição (motor EA211).",
        "normas": ["OEM VAG"],
        "especificacoes": ["Inclui vedante", "Trocar com o kit de distribuição"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "SEAT Ibiza 1.0 TSI", "VW Polo 1.0 TSI"],
        "referencias": ["VW 04C109479H"],
        "marcas": {
            "original": "INA / Schaeffler (fabricante OEM)",
            "equivalente": "ContiTech, Gates, SKF",
            "economica": "Blue Print, RIDEX",
        },
        "dica": "A bomba de água vem incluída no kit INA da distribuição. Troque-a sempre em conjunto para não abrir o motor duas vezes.",
        "quando_trocar": "Com o kit de distribuição (cada ~120.000 km / 6 anos).",
        "quantidade": "1 unidade.",
    },
    {
        "id": "termostato",
        "nome": "Termóstato do motor (com corpo)",
        "categoria": "motor-ignicao",
        "descricao": "Termóstato com corpo/casa para motores EA211; regula a temperatura de funcionamento do motor.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Abertura ~87 °C", "Com corpo (housing)"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Ibiza 1.0 TSI", "VW Polo 1.0 TSI"],
        "referencias": ["VW 04C121111", "VW 04C121115"],
        "marcas": {
            "original": "INA / Mahle (OEM)",
            "equivalente": "Wahler, Gates",
            "economica": "Blue Print, Hutchinson",
        },
        "dica": "Se a agulha de temperatura nunca atinge os 90 °C, o termóstato está preso aberto. Troque o corpo junto para evitar fugas de líquido.",
        "quando_trocar": "Quando falha ou a cada 120.000 km.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "suporte-do-motor",
        "nome": "Suporte do motor (coxim)",
        "categoria": "motor-ignicao",
        "descricao": "Coxim que absorve as vibrações do motor e fixa o grupo ao chassis.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Trocar em conjunto com o coxim da caixa"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Ibiza 1.0 TSI"],
        "referencias": ["VW 6F0199262", "VW 6F0199273"],
        "marcas": {
            "original": "SEAT / VW (OEM)",
            "equivalente": "Corteco, Febi",
            "economica": "Marca branca (verificar qualidade)",
        },
        "dica": "Vibração ao relantim e ruído ao engatar indicam coxim gasto. Troque os dois coxins (motor e caixa) em conjunto.",
        "quando_trocar": "Quando vibrar ou a partir dos 100.000 km.",
        "quantidade": "2 unidades.",
    },
    {
        "id": "sensor-pressao-oleo",
        "nome": "Sensor de pressão do óleo",
        "categoria": "motor-ignicao",
        "descricao": "Interruptor de pressão de óleo que acende a luz de aviso quando a pressão cai.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Rosca M10x1 (confirmar por VIN)"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Ibiza 1.0 TSI", "VW Polo 1.0 TSI"],
        "referencias": ["VW 04E919081"],
        "marcas": {
            "original": "Hella / Febi (OEM)",
            "equivalente": "Bosch",
            "economica": "Genérico",
        },
        "dica": "Luz de óleo acesa com óleo no nível correto = sensor avariado. Confirme primeiro a pressão real antes de trocar apenas o sensor.",
        "quando_trocar": "Quando falha.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "tambores-travao",
        "nome": "Tambores de travão traseiros",
        "categoria": "travagem",
        "descricao": "Tambores traseiros para as versões do Arona com travão de tambor no eixo traseiro.",
        "normas": ["ECE R90"],
        "especificacoes": ["Diâmetro a confirmar por VIN"],
        "aplicacoes": ["SEAT Arona 1.0 TSI 95cv (com tambores)", "SEAT Ibiza"],
        "referencias": ["VW (verificar por VIN)"],
        "marcas": {
            "original": "TRW (OEM)",
            "equivalente": "Brembo, Textar",
            "economica": "RIDEX, A.B.S.",
        },
        "dica": "Nos tambores, troque também os sapatos (calços) e, se houver fuga, os cilindros de roda.",
        "quando_trocar": "Quando houver ondulação, folga ou ruído.",
        "quantidade": "2 tambores + sapatos.",
    },
    {
        "id": "tubos-travao",
        "nome": "Tubos e traçadores de travão",
        "categoria": "travagem",
        "descricao": "Traçadores flexíveis de travão dianteiros e traseiros; fissuras comprometem a travagem.",
        "normas": ["ECE R90"],
        "especificacoes": ["Comprimento específico por eixo"],
        "aplicacoes": ["SEAT Arona (dianteiros/traseiros)"],
        "referencias": ["VW 6F0611701", "VW 6F0611702"],
        "marcas": {
            "original": "ATE (OEM)",
            "equivalente": "Bosch, Febi",
            "economica": "Genérico ECE R90",
        },
        "dica": "Traçadores fendilhados ou inchados podem rebentar ao travar. Verifique-os sempre que trocar pastilhas.",
        "quando_trocar": "A cada 60.000 km ou se fendilhado.",
        "quantidade": "2 dianteiros + 2 traseiros.",
    },
    {
        "id": "sensor-abs",
        "nome": "Sensor de rotação da roda (ABS/ESC)",
        "categoria": "travagem",
        "descricao": "Sensor de velocidade da roda para o sistema ABS/ESC; avaria acende as luzes no painel.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Dianteiro/traseiro", "Confirmar lado"],
        "aplicacoes": ["SEAT Arona (todas as rodas)"],
        "referencias": ["VW 5Q0927807A", "VW 5Q0927808A"],
        "marcas": {
            "original": "Bosch / Continental (OEM)",
            "equivalente": "Febi",
            "economica": "Genérico",
        },
        "dica": "Luz ABS + ESC acesa é quase sempre um sensor de roda. Diagnostique com scanner (VCDS/OBDeleven) antes de comprar para acertar o lado.",
        "quando_trocar": "Quando a luz acende.",
        "quantidade": "1 sensor (confirmar lado).",
    },
    {
        "id": "amortecedores",
        "nome": "Amortecedores dianteiros",
        "categoria": "suspensao-direcao",
        "descricao": "Amortecedores dianteiros do Arona; trocar em par e de preferência com batentes e rolamentos.",
        "normas": ["ECE R90 (equivalência)"],
        "especificacoes": ["Trocar em par por eixo", "Com batentes (kit)"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI", "SEAT Arona 1.6 TDI"],
        "referencias": ["VW 6F0413031N", "VW 6F0413031M"],
        "marcas": {
            "original": "Sachs / Bilstein (OEM)",
            "equivalente": "Monroe, KYB",
            "economica": "Delphi (custo-médio)",
        },
        "dica": "Amortecedor gasto causa oscilação ao passar lombas e aumento da distância de travagem. Compre o par completo com batentes (kit).",
        "quando_trocar": "A cada ~80.000-100.000 km ou se pingar óleo.",
        "quantidade": "2 dianteiros + batentes.",
    },
    {
        "id": "bracos-suspensao",
        "nome": "Braços de suspensão dianteiros",
        "categoria": "suspensao-direcao",
        "descricao": "Braços triangulares inferiores com rótula integrada; desgaste causa folga na direção e ruído.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Trocar em par", "Com rótula integrada"],
        "aplicacoes": ["SEAT Arona", "SEAT Ibiza", "VW Polo", "VW T-Cross"],
        "referencias": ["VW 6F0407151"],
        "marcas": {
            "original": "Lemförder / TRW (OEM)",
            "equivalente": "Febi, Moog",
            "economica": "Blue Print",
        },
        "dica": "Ruído 'clunk' ao virar ou passar buracos = braço gasto. Troque o par completo (braço + rótula integrada).",
        "quando_trocar": "Quando houver folga (teste de jogo).",
        "quantidade": "2 braços.",
    },
    {
        "id": "rotulas",
        "nome": "Rótulas de suspensão",
        "categoria": "suspensao-direcao",
        "descricao": "Rótula da suspensão dianteira que liga o braço ao cubo da roda.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Verificar folga com alavanca"],
        "aplicacoes": ["SEAT Arona (dianteiras)"],
        "referencias": ["VW 6F0407365B"],
        "marcas": {
            "original": "Lemförder (OEM)",
            "equivalente": "Febi, Moog",
            "economica": "Blue Print",
        },
        "dica": "Rótula com folga deve ser trocada imediatamente — pode partir em andamento e provocar acidente.",
        "quando_trocar": "Quando houver folga.",
        "quantidade": "2 rótulas.",
    },
    {
        "id": "bieletas-estabilizador",
        "nome": "Bieletas da barra estabilizadora",
        "categoria": "suspensao-direcao",
        "descricao": "Bieletas que ligam a barra estabilizadora à suspensão; desgaste causa ruído metálico.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Dianteiras e/ou traseiras"],
        "aplicacoes": ["SEAT Arona (dianteiras)"],
        "referencias": ["VW 6F0411314B"],
        "marcas": {
            "original": "Lemförder / Febi (OEM)",
            "equivalente": "Moog",
            "economica": "Blue Print",
        },
        "dica": "Ruído 'tac-tac' ao passar lombas é quase sempre bieleta gasta — peça barata e fácil de trocar.",
        "quando_trocar": "Quando houver ruído.",
        "quantidade": "2 bieletas dianteiras.",
    },
    {
        "id": "terminais-direcao",
        "nome": "Terminais de direção",
        "categoria": "suspensao-direcao",
        "descricao": "Extremidades da barra de direção que ligam ao cubo da roda; folga causa desalinhamento.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Exige alinhamento após troca"],
        "aplicacoes": ["SEAT Arona (dianteiros)"],
        "referencias": ["VW 6F0419810A"],
        "marcas": {
            "original": "Lemförder / TRW (OEM)",
            "equivalente": "Febi",
            "economica": "Blue Print",
        },
        "dica": "Após trocar terminais, faça sempre o alinhamento da direção (geometria).",
        "quando_trocar": "Quando houver folga.",
        "quantidade": "2 terminais.",
    },
    {
        "id": "kit-embraiagem",
        "nome": "Kit de embraiagem (disco, prato, rolamento)",
        "categoria": "transmissao-embraiagem",
        "descricao": "Kit completo de embraiagem para Arona 1.0 TSI com caixa manual MQ281.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Inclui rolamento de encosto"],
        "aplicacoes": ["SEAT Arona 1.0 TSI (manual)", "SEAT Ibiza 1.0 TSI"],
        "referencias": ["VW 04E141015X"],
        "marcas": {
            "original": "LuK / Sachs (OEM)",
            "equivalente": "Sachs, Valeo",
            "economica": "Blue Print",
        },
        "dica": "O fabricante OEM da embraiagem VAG é a LuK (Schaeffler). Comprar o kit LuK custa cerca de 40% menos que a caixa VW e é a mesma peça.",
        "quando_trocar": "Quando patina ou vibra (~150.000-200.000 km).",
        "quantidade": "1 kit completo.",
    },
    {
        "id": "homocineticas",
        "nome": "Eixos de transmissão (homocinéticas)",
        "categoria": "transmissao-embraiagem",
        "descricao": "Semi-eixos com juntas homocinéticas dianteiros; juntas gastas fazem estalidos ao virar.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Dianteiros esquerdo/direito"],
        "aplicacoes": ["SEAT Arona 1.0 TSI (dianteiros)"],
        "referencias": ["VW 5Q0407271BA"],
        "marcas": {
            "original": "GKN (OEM)",
            "equivalente": "GSP, Febi",
            "economica": "Blue Print",
        },
        "dica": "Estalidos ao virar com aceleração = junta gasta. Troque o eixo completo (fica mais barato que reparar a junta).",
        "quando_trocar": "Quando as juntas furam.",
        "quantidade": "1 eixo (confirmar lado).",
    },
    {
        "id": "suporte-caixa",
        "nome": "Suporte (coxim) da caixa de velocidades",
        "categoria": "transmissao-embraiagem",
        "descricao": "Coxim da caixa de velocidades; vibração e engates duros indicam desgaste.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Trocar em conjunto com o coxim do motor"],
        "aplicacoes": ["SEAT Arona (manual/DSG)"],
        "referencias": ["VW 6F0199855A"],
        "marcas": {
            "original": "SEAT / VW (OEM)",
            "equivalente": "Corteco, Febi",
            "economica": "Marca branca",
        },
        "dica": "Se engatar dá 'estalo' e há vibração, verifique os dois coxins (motor e caixa) — são baratos e fáceis de trocar.",
        "quando_trocar": "Quando vibrar.",
        "quantidade": "1 coxim.",
    },
    {
        "id": "silenciador",
        "nome": "Silenciador traseiro do escape",
        "categoria": "escapamento",
        "descricao": "Silenciador traseiro (muffler) do Arona; ruído forte indica furo no corpo.",
        "normas": ["E-mark (ECE R51)"],
        "especificacoes": ["Recorte específico do Arona"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.6 TDI"],
        "referencias": ["VW 6F0253609H"],
        "marcas": {
            "original": "Eberspächer (OEM)",
            "equivalente": "Bosal, Walker",
            "economica": "Genérico E-mark",
        },
        "dica": "Um silenciador Bosal custa metade do original e cumpre o mesmo E-mark de homologação.",
        "quando_trocar": "Quando furar ou ficar ruidoso.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "catalisador",
        "nome": "Catalisador (conversor catalítico)",
        "categoria": "escapamento",
        "descricao": "Catalisador do Arona 1.0 TSI; falha acende a luz do motor (código P0420).",
        "normas": ["Emissões Euro 6d"],
        "especificacoes": ["Específico do motor 1.0 TSI"],
        "aplicacoes": ["SEAT Arona 1.0 TSI", "SEAT Arona 1.5 TSI"],
        "referencias": ["VW 6F0131711"],
        "marcas": {
            "original": "Eberspächer / Faurecia (OEM)",
            "equivalente": "Bosal, Klarius",
            "economica": "Genérico",
        },
        "dica": "O código P0420 nem sempre significa catalisador gasto — pode ser a sonda lambda. Diagnostique com scanner antes de comprar.",
        "quando_trocar": "Quando entupir ou o código P0420 for confirmado.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "filtro-particulas-dpf",
        "nome": "Filtro de partículas (DPF) — 1.6 TDI",
        "categoria": "escapamento",
        "descricao": "Filtro de partículas diesel com regeneração automática; entope em trajetos curtos.",
        "normas": ["Emissões Euro 6"],
        "especificacoes": ["Específico do 1.6 TDI"],
        "aplicacoes": ["SEAT Arona 1.6 TDI"],
        "referencias": ["VW 6F0254101"],
        "marcas": {
            "original": "Eberspächer / Faurecia (OEM)",
            "equivalente": "Bosal",
            "economica": "Genérico",
        },
        "dica": "Evite entupimentos fazendo pelo menos 20 minutos de autoestrada por semana. Se entupir, tente a regeneração forçada via scanner antes de trocar.",
        "quando_trocar": "Quando a regeneração não resolve (~150.000-200.000 km).",
        "quantidade": "1 unidade.",
    },
    {
        "id": "sonda-lambda",
        "nome": "Sonda lambda (sensor de oxigénio)",
        "categoria": "escapamento",
        "descricao": "Sonda lambda antes/depois do catalisador; avaria aumenta o consumo e acende a luz do motor.",
        "normas": ["OEM VAG"],
        "especificacoes": ["Dianteira (regulação) / traseira (diagnóstico)"],
        "aplicacoes": ["SEAT Arona 1.0 TSI"],
        "referencias": ["VW 04C906262AF"],
        "marcas": {
            "original": "Bosch / NTK (OEM)",
            "equivalente": "Bosch, NTK",
            "economica": "Genérico",
        },
        "dica": "O sensor OEM dos VAG é Bosch ou NTK — compre pela marca fabricante e não pela embalagem VW, poupando 30-50%.",
        "quando_trocar": "Quando falha (códigos P0130/P0134).",
        "quantidade": "1 sonda (confirmar posição).",
    },
    {
        "id": "junta-flexivel",
        "nome": "Junta flexível do escape",
        "categoria": "escapamento",
        "descricao": "Junta flexível que absorve as vibrações do motor no sistema de escape.",
        "normas": ["E-mark"],
        "especificacoes": ["Diâmetro específico do tubo"],
        "aplicacoes": ["SEAT Arona (todos os motores)"],
        "referencias": ["Verificar diâmetro do sistema"],
        "marcas": {
            "original": "Walker (OEM)",
            "equivalente": "Bosal",
            "economica": "Genérico",
        },
        "dica": "Ruído metálico ao acelerar pode ser a flexível fendilhada — é barata e rápida de substituir.",
        "quando_trocar": "Quando fendilhar.",
        "quantidade": "1 unidade.",
    },
    {
        "id": "lampadas-traseiras",
        "nome": "Lâmpadas traseiras (stop/pisca/posição)",
        "categoria": "eletricidade-iluminacao",
        "descricao": "Lâmpadas de travagem (P21W), piscas (PY21W) e posição (T10W) do Arona.",
        "normas": ["ECE R37"],
        "especificacoes": ["P21W (stop)", "PY21W (pisca)", "T10W (posição)"],
        "aplicacoes": ["SEAT Arona"],
        "referencias": ["Philips P21W", "Osram PY21W"],
        "marcas": {
            "original": "Philips / Osram (OEM)",
            "equivalente": "Bosch",
            "economica": "Genérico E-mark",
        },
        "dica": "LED de substituição (com resistor canbus) emite luz branca — verifique a homologação E-mark para não falhar na inspeção.",
        "quando_trocar": "Quando queimam.",
        "quantidade": "2-4 lâmpadas.",
    },
    {
        "id": "lampadas-matricula",
        "nome": "Lâmpadas de matrícula (C5W)",
        "categoria": "eletricidade-iluminacao",
        "descricao": "Lâmpadas da matrícula traseira; avaria comum nos VAG.",
        "normas": ["ECE R37"],
        "especificacoes": ["C5W 12V 5W"],
        "aplicacoes": ["SEAT Arona"],
        "referencias": ["Philips C5W"],
        "marcas": {
            "original": "Philips / Osram (OEM)",
            "equivalente": "Bosch",
            "economica": "Genérico",
        },
        "dica": "As lâmpadas de matrícula queimam com frequência — leve sempre um par de reserva no carro.",
        "quando_trocar": "Quando queimam.",
        "quantidade": "2 lâmpadas.",
    },
    {
        "id": "sensores-estacionamento",
        "nome": "Sensores de estacionamento (PAS)",
        "categoria": "eletricidade-iluminacao",
        "descricao": "Sensores ultrassónicos do sistema de estacionamento traseiro (ParkPilot).",
        "normas": ["OEM VAG"],
        "especificacoes": ["Específicos por versão (pintados)"],
        "aplicacoes": ["SEAT Arona com ParkPilot"],
        "referencias": ["VW 6F0919275D"],
        "marcas": {
            "original": "Valeo / Hella (OEM)",
            "equivalente": "Hella, Valeo",
            "economica": "Genérico",
        },
        "dica": "Se um sensor falha, o sistema desliga por completo. Identifique o avariado com o scanner ou pelo som antes de comprar.",
        "quando_trocar": "Quando avaria.",
        "quantidade": "1 sensor.",
    },
]

DICAS_GERAIS = [
    {
        "titulo": "Compre pela referência OEM, não pela marca do concessionário",
        "texto": "As peças VAG originais são fabricadas por marcas como Mann, Bosch, TRW, Textar, INA, NGK, Varta. Pesquise a referência OEM (ex.: 04E115561C) e compre a mesma peça pela marca fabricante — poupa 30-60%.",
    },
    {
        "titulo": "Use o VIN e a matrícula para confirmar peças",
        "texto": "Sites como Autodoc, Oscaro e Mister-Auto permitem pesquisar por matrícula/VIN. Confirme sempre o código do motor (ex.: CHZB para o 1.0 TSI) antes de comprar.",
    },
    {
        "titulo": "Marcas 'white label' com boa relação qualidade/preço",
        "texto": "Filtros Filtron/CoopersFiaam, pastilhas Ferodo/Valeo, discos A.B.S./RIDEX e óleos Mannol/Comma certificados com a norma VAG são opções fiáveis a preço baixo.",
    },
    {
        "titulo": "Intervalos de manutenção LongLife",
        "texto": "O Arona a gasolina usa intervalo LongLife (até 30.000 km/2 anos). Se o carro faz muitos km em cidade, encurte para 15.000 km/1 ano para proteger o motor.",
    },
    {
        "titulo": "Peças de segurança: não poupe no que trava ou vira",
        "texto": "Pastilhas, discos e pneus devem cumprir ECE R90 e etiqueta UE. Poupe no conforto (tapetes, suportes), mas não na segurança (travagem, direção, pneus).",
    },
    {
        "titulo": "Registo de bateria e recuo do travão elétrico",
        "texto": "Ao trocar a bateria (start-stop) ou as pastilhas traseiras (EPB), é preciso registo/codificação. Um OBDeleven ou VCDS resolve — ou peça só esse serviço à oficina.",
    },
    {
        "titulo": "Compare sempre a etiqueta UE dos pneus",
        "texto": "Dois pneus da mesma medida podem ter rolagem, aderência em molhado e ruído muito diferentes. O pneu mais barato pode custar mais em combustível ao longo da vida.",
    },
]
